### ISSUE TITLE
Add helpful command aliases

### ISSUE THREAD

**Issue by Jonxslays** [nusex/nusex#37]
### Summary

I was recently working with nusex and i was looking at profiles. I wanted to know what profiles, if any, I had up until now. My first thought was to use `nusex profile --list` or `nusex profile ls` but these obviously these did not work.

After running `nusex --help` I realized I could get the information I wanted via `nusex list`. 

### Problem

My first instinct was to use a command that does not exist, meaning maybe this is a great place for an alias to help new users get started with nusex.

### Parts of nusex that will benefit

- [X] CLI
- [ ] API

### Ideal implementation

Implement helpful command aliases for subcommands. ~~This could also be applied to the `nusex template` subcommand I think~~ (There is no template subcommand). Maybe others if we give it some thought.

Maybe I could look at contributing this if you like the idea.  

### Contribution

- [X] I wish to contribute this feature.

### Checklist

- [X] I have searched the issue tracker for duplicate issues and couldn't find any. If this is a follow-up issue, I have specified as such.

**Comment by parafoxia** [comment]
This would actually be pretty cool! I'm not 100% sure how you'd trigger the other command -- perhaps importing the CLI commands into eachother would work?

Either way, if you wanna give this a shot, go for it.

**Comment by Jonxslays** [comment]
Cool, I'll take a look this weekend.
