### ISSUE TITLE
Typo in help message

### ISSUE THREAD

**Issue by Jonxslays** [nusex/nusex#39]
### Steps to reproduce

1. Run `nusex --help`

### Expected behaviour

It will be a grammatically correct help message ;)

### Current behaviour

  `-i, --info            show detailed information for nusex exit`

### System information

nusex 1.2.4.post1
CPython 3.10.0 GCC 11.1.0
Linux 5.10.83-1-lts
└──Arch Linux

### Checklist

- [X] I have searched the issue tracker for duplicate issues and couldn't find any. If this is a follow-up issue, I have specified as such.

**Comment by parafoxia** [comment]
This is a big oof lmao. I'll make sure that gets patched for the next release.

**Comment by Jonxslays** [comment]
I tried to look for for where that line comes from and literally couldn't find it, otherwise I would have just fixed it lol.

**Comment by parafoxia** [comment]
It's in the main CLI file where all the subcommands are created.
